import model from './form-model'

const { client, lawyer } = model

export default {
  client: {
    [client.fields.firstName.name]: '',
    [client.fields.lastName.name]: '',
    [client.fields.email.name]: '',
    [client.fields.phone.name]: '',
    [client.fields.password.name]: '',
    [client.fields.confirmPassword.name]: '',
    [client.fields.userAgreement.name]: false,
    recaptcha: '',
  },
  lawyer: {
    [lawyer.fields.lawyerType.name]: '',
    [lawyer.fields.firstName.name]: '',
    [lawyer.fields.lastName.name]: '',
    [lawyer.fields.email.name]: '',
    [lawyer.fields.phone.name]: '',
    [lawyer.fields.password.name]: '',
    [lawyer.fields.confirmPassword.name]: '',
    [lawyer.fields.userAgreement.name]: false,
    [lawyer.fields.professions.name]: [],
    [lawyer.fields.languages.name]: '',
    [lawyer.fields.licences.name]: [],
    // [lawyer.fields.professionalLicence.name]: '',
    // [lawyer.fields.licenceYear.name]: '',
    // [lawyer.fields.licenceCountry.name]: '',
    // [lawyer.fields.licenceRegion.name]: '',
    [lawyer.fields.firmId.name]: '',
    [lawyer.fields.firmInviteEmail.name]: '',
    [lawyer.fields.firmName.name]: '',
    [lawyer.fields.firmStreetNumber.name]: '',
    [lawyer.fields.firmStreetName.name]: '',
    [lawyer.fields.firmAppSuite.name]: '',
    [lawyer.fields.firmCountry.name]: '',
    [lawyer.fields.firmProvinceState.name]: '',
    [lawyer.fields.firmCity.name]: '',
    [lawyer.fields.firmPostalZipCode.name]: '',
    [lawyer.fields.firmPhone.name]: '',
    [lawyer.fields.firmFax.name]: '',
    [lawyer.fields.paymentEmail.name]: '',
    [lawyer.fields.firmTaxTPS.name]: '',
    [lawyer.fields.firmTaxTVQ.name]: '',
    [lawyer.fields.firmOmitTaxAgreement.name]: false,
    [lawyer.fields.employeesInviteEmails.name]: [],
    recaptcha: '',
  },
}
